---
settings:
  name: GenAI
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos do GenAI
    url: "/index.html"
  - title: Notas de lançamento
    entries:
    - title: O que há de novo
      url: "/whats-new.html"
  - title: Saiba mais sobre a fábrica de cargas de trabalho da BlueXP  para o GenAI
    entries:
    - title: Saiba mais sobre a fábrica de cargas de trabalho da BlueXP  para o GenAI
      url: "/general/ai-workloads-overview.html"
    - title: Componentes do motor NetApp GenAI
      url: "/general/genai-engine-instance.html"
  - title: Use o GenAI para criar bases de conhecimento para a Amazon bedrock
    entries:
    - title: Comece agora
      entries:
      - title: Início rápido
        url: "/knowledge-base/quick-start-knowledge-base.html"
      - title: Requisitos da base de conhecimento
        url: "/knowledge-base/requirements-knowledge-base.html"
      - title: Identificar fontes de dados para adicionar a uma base de conhecimento
        url: "/knowledge-base/identify-data-sources-knowledge-base.html"
      - title: Implantar a infraestrutura do GenAI
        url: "/knowledge-base/deploy-infrastructure.html"
    - title: Crie uma base de conhecimento
      url: "/knowledge-base/create-knowledgebase.html"
    - title: Teste uma base de conhecimento
      url: "/knowledge-base/test-knowledgebase.html"
    - title: Ative a autenticação
      url: "/knowledge-base/activate-authentication.html"
    - title: Publique uma base de conhecimento
      url: "/knowledge-base/publish-knowledgebase.html"
    - title: Use o aplicativo de exemplo de chatbot externo
      url: "/knowledge-base/example-chatbot-application.html"
    - title: Crie um aplicativo de IA baseado em RAG
      url: "/knowledge-base/create-application.html"
    - title: O que você pode fazer a seguir
      url: "/knowledge-base/whats-next.html"
  - title: Use o GenAI para criar conetores para o Amazon Q Business
    entries:
    - title: Comece agora
      entries:
      - title: Início rápido
        url: "/connector/quick-start-connector.html"
      - title: Requisitos do conetor
        url: "/connector/requirements-connector.html"
      - title: Identificar fontes de dados para adicionar a um conetor
        url: "/connector/identify-data-sources-connector.html"
      - title: Implantar a infraestrutura do GenAI
        url: "/connector/deploy-infrastructure.html"
    - title: Crie um conector NetApp para o Amazon Q Business
      url: "/connector/define-connector.html"
  - title: Administrar e monitorar
    entries:
    - title: Gerenciar a infraestrutura do GenAI
      url: "/general/manage-infrastructure.html"
    - title: Gerenciar bases de conhecimento
      url: "/knowledge-base/manage-knowledgebase.html"
    - title: Gerenciar conetores
      url: "/connector/manage-connector.html"
    - title: Gerenciar fontes de dados
      url: "/general/manage-data-source.html"
    - title: Monitore as operações com o Tracker
      url: "/general/monitor-operations.html"
  - title: Conhecimento e apoio
    entries:
    - title: Registre-se para obter suporte
      url: "/support-registration.html"
    - title: Solução de problemas
      url: "/general/troubleshooting.html"
    - title: Obtenha ajuda
      url: "/get-help.html"
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: BlueXP workload factory
  repo: workload-family
