---
sidebar: sidebar 
permalink: troubleshooting.html 
keywords: support registration, register for support, support, nss account, add nss account, 
summary: Antes de poder abrir um caso de suporte com o suporte técnico da NetApp, você precisa adicionar uma conta do site de suporte da NetApp à fábrica de carga de trabalho e, em seguida, Registrar-se para suporte. 
---
= Solução de problemas
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Aprenda a contornar alguns problemas comuns que você pode encontrar.



== Problemas e soluções comuns

Se você tiver um desses problemas, use as etapas na coluna solução alternativa para tentar resolvê-lo.

[cols="1,2,2,4"]
|===
| Área | Problema | Causa | Solução alternativa 


| Implantação | A implantação falha porque o volume já existe. | A fábrica de carga de trabalho do GenAI precisa criar um novo volume durante o processo de implantação, mas já existe um volume usando o nome especificado. | Especifique um nome exclusivo a ser usado para o novo volume e tente implantar novamente. 


| Implantação | A implantação falha porque a fábrica de carga de trabalho do GenAI não consegue montar o volume. | Uma ou mais portas de entrada necessárias para o FSX for NetApp ONTAP são fechadas ou filtradas.  a| 
Abra as portas listadas em https://docs.netapp.com/us-en/bluexp-fsx-ontap/requirements/reference-security-groups-fsx.html#inbound-rules["Regras do grupo de segurança para o FSX for ONTAP"^].



| Manutenção | A instância do Docker de back-end usada pela fábrica de carga de trabalho para o GenAI falhou ao iniciar. | O volume foi excluído e a instância EC2 foi reiniciada.  a| 
Use as seguintes etapas de recuperação:

.Passos
. Crie um novo volume no FSX for NetApp ONTAP. Por exemplo, o nome do volume pode ser `netapp_ai` e o caminho do volume pode ser `/netapp_ai`.
. SSH para a instância do Amazon EC2.
. Listar os volumes:
+
[source, console]
----
docker volume list
----
. Retire o volume antigo:
+
[source, console]
----
docker volume rm ec2-user_persistent_folder
----
. Abra o `docker-compose.yml` arquivo usando um editor de texto.
.  `volumes`Na secção , altere o caminho do dispositivo para o novo caminho do volume. Por exemplo:
+
[source, yaml]
----
volumes:
  persistent_folder:
    driver_opts:
      type: 'nfs'
      o: "addr=svm-0df66b96a890d8a72.\
      fs-0d673008aaca12bc3.\
      fsx.us-east-1.amazonaws.com,nolock,soft,rw"
      device: ':/netapp_ai' # Path to new volume
----




| Manutenção | A instância do Docker de back-end usada pela fábrica de carga de trabalho para o GenAI falhou ao iniciar. | O volume raiz foi excluído. | Crie um volume com um nome e um caminho e reinicie a instância do Docker de back-end do Amazon EC2. 
|===