---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: Saiba o que há de novo com a funcionalidade de workloads de IA da fábrica de workloads. 
---
= Novidades na fábrica de workloads da BlueXP  para a GenAI
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Saiba o que há de novo com a capacidade generativa de cargas de trabalho de IA da fábrica de cargas de trabalho.



== 30 de março de 2025



=== Suporte aprimorado ao tipo de arquivo

Esta versão do GenAI introduz suporte ao formato de arquivo JSON e JSONP ao criar `.json` arquivos de fontes de dados. Arquivos JSON com objetos aninhados são suportados, com suporte limitado para arrays aninhados.

link:https://review.docs.netapp.com/us-en/workload-genai_mar-2-release/identify-data-sources.html#supported-data-source-file-formats["Formatos de arquivo de origem de dados suportados"]



=== Suporte de internacionalização para o aplicativo de amostra de chatbot externo

Agora você pode facilmente alterar a interface do usuário do aplicativo de chatbot externo de amostra do GenAI para um idioma ou localidade diferente.

link:https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/AI/GenAI-ChatBot-application-sample#netapp-workload-factory-genai-sample-application["Aplicação de chatbot de amostra externa GenAI"]



=== Suporte para o modelo de bate-papo Anthropologic Claude Sonnet 3,7

O GenAI agora inclui suporte para o modelo de bate-papo Anthropologic Claude 3,7 Sonnet. Os recursos beta do Claude 3,7 Sonnet permitem até 128K tokens de saída por solicitação e suportam novas ações de uso do computador. Claude 3,7 Sonnet modo de pensamento estendido será suportado em um futuro lançamento do GenAI.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html["Crie uma base de conhecimento do GenAI"]



=== Suporte para adicionar fontes de dados de compartilhamentos genéricos NFS/SMB

Usando a API de fábrica de carga de trabalho, agora você pode adicionar uma fonte de dados de um compartilhamento genérico NFSv3, NFSv4 ou SMB. Quando você adiciona uma fonte de dados de um compartilhamento NFS ou SMB, o volume da base de conhecimento permanece em um volume do Amazon FSX for NetApp ONTAP. A IU da Web de fábrica da carga de trabalho suportará esse recurso em uma versão futura.

link:https://console.workloads.netapp.com/api-doc["Use a API de fábrica da carga de trabalho"^]



=== Suporte a peering VPC

Agora você pode implantar a infraestrutura do GenAI em toda a link:https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html["Nuvens privadas virtuais (VPCs)"^]região e usar a mesma conta da AWS. Você pode implantar o mecanismo de AI em uma VPC e, em seguida, criar uma base de conhecimento em uma VPC com peered e selecionar sistemas de arquivos do Amazon FSX for NetApp ONTAP que residem em uma VPC com peered.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html["Crie uma base de conhecimento do GenAI"]



== 02 de março de 2025



=== Aprimoramentos de chatbot incorporados

Agora você pode copiar perguntas e respostas diretamente para a área de transferência, ajustar o tamanho da janela de bate-papo e alterar seu título. Além disso, as respostas de bate-papo agora podem incluir tabelas, que também são copiáveis.

link:https://docs.netapp.com/us-en/workload-genai/test-knowledgebase.html["Teste uma base de conhecimento do GenAI"]



=== Suporte a citações de resposta de chat

As respostas de bate-papo agora incluem citações que listam os arquivos e blocos de dados que foram usados para gerar a resposta.

link:https://docs.netapp.com/us-en/workload-genai/test-knowledgebase.html["Teste uma base de conhecimento do GenAI"]



=== Suporte aprimorado ao tipo de arquivo

Esta versão do GenAI oferece suporte aprimorado a arquivos:

* Os modelos de chat apresentam suporte CSV melhorado. Isso permite respostas mais úteis ao consultar dados de arquivos CSV.
* O GenAI agora pode ingerir arquivos Apache Parquet a partir de fontes de dados.
* O GenAI agora suporta a introdução de arquivos DOCX do Microsoft Word que incluem imagens.


link:https://review.docs.netapp.com/us-en/workload-genai_mar-2-release/identify-data-sources.html#supported-data-source-file-formats["Formatos de arquivo de origem de dados suportados"]



== 02 de fevereiro de 2025



=== Suporte para modelos de fundação Amazon Nova

O GenAI agora suporta os modelos de fundação Amazon Nova. São suportados Amazon Nova Micro, Amazon Nova Lite e Amazon Nova Pro.

link:https://docs.netapp.com/us-en/workload-genai/requirements.html["Requisitos do GenAI"]



=== Filtragem do tipo de arquivo para fontes de dados

O GenAI agora suporta a seleção de tipos de arquivo específicos para incluir na digitalização da fonte de dados quando você adiciona uma fonte de dados.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["Adicione fontes de dados à base de conhecimento"]



=== Filtragem de data de modificação de arquivo para fontes de dados

O GenAI agora suporta arquivos de filtragem para incluir na verificação da fonte de dados por data de modificação quando você adiciona uma fonte de dados. Você pode escolher um intervalo de datas de modificação para os arquivos incluídos.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["Adicione fontes de dados à base de conhecimento"]



=== Suporte para arquivos de imagem e suporte aprimorado para arquivos PDF

O GenAI agora suporta a digitalização de arquivos de imagem e imagens dentro de arquivos PDF (também conhecido como suporte a arquivos multimodais). Se você escolher arquivos de imagem, o texto das imagens é digitalizado para a fonte de dados e usado como dados. Essa capacidade inclui imagens em documentos PDF; se você incluir tipos de arquivo PDF, as imagens em cada PDF são digitalizadas para texto e esse texto é incluído nas informações da fonte de dados.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["Adicione fontes de dados à base de conhecimento"]



=== Pesquisa híbrida e suporte de reclassificação

O GenAI agora aumenta a relevância dos resultados de pesquisa usando a pesquisa híbrida e reclassificando os resultados. A pesquisa híbrida combina buscas de palavras-chave com busca vetorial e semântica. Os resultados padrão de pesquisa de palavras-chave são aumentados com correspondências próximas e nuance linguística, aumentando a relevância. O GenAI reclassifica os resultados da pesquisa e apenas retorna resultados com a maior relevância.

link:https://docs.netapp.com/us-en/workload-genai/ai-workloads-overview.html#benefits-of-using-genai-to-create-generative-ai-applications["Saiba mais sobre a fábrica de cargas de trabalho da BlueXP  para o GenAI"]



== 05 de janeiro de 2025



=== Nome do instantâneo personalizado

Agora você pode fornecer um nome de instantâneo para um instantâneo ad-hoc.

link:https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html#protect-a-knowledge-base-with-snapshots["Proteja uma base de conhecimento com snapshots"]



=== Nome de instância personalizado do mecanismo de AI

Agora você pode dar um nome personalizado à instância do mecanismo de AI durante a implantação.

link:https://docs.netapp.com/us-en/workload-genai/deploy-infrastructure.html["Implantar a infraestrutura do GenAI"]



=== Reconstruir a infraestrutura do GenAI corrompida ou ausente

Se a instância do seu mecanismo de AI ficar corrompida ou for excluída, você pode deixar que a carga de trabalho reconstrua-a de fábrica para você. A fábrica de carga de trabalho reanexa automaticamente suas bases de conhecimento à infraestrutura após a conclusão da reconstrução, para que elas estejam prontas para uso.

link:https://docs.netapp.com/us-en/workload-genai/troubleshooting.html["Solução de problemas"]



== 01 de dezembro de 2024



=== Clonar uma base de conhecimento a partir de um instantâneo

Agora, a fábrica de workloads da BlueXP  para o GenAI é compatível com a clonagem de uma base de conhecimento a partir de um snapshot. Isso permite a recuperação rápida de bases de conhecimento e a criação de novas bases de conhecimento com fontes de dados existentes, além de ajudar na recuperação e desenvolvimento de dados.

link:https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html#clone-a-knowledge-base["Clonar uma base de conhecimento"]



=== Detecção e replicação de clusters ONTAP no local

Descubra e replique dados de cluster do ONTAP no local para um sistema de arquivos FSX for ONTAP para que ele possa ser usado para enriquecer bases de conhecimento de IA. Todos os fluxos de trabalho de descoberta e replicação no local são possíveis a partir da nova guia *On-Premise ONTAP* no inventário de armazenamento.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/use-onprem-data.html["Descubra um cluster ONTAP no local"]



== 3 de novembro de 2024



=== Mascarar informações pessoais identificáveis com guardrails de dados

A carga de trabalho generativa de IA apresenta o recurso de guardrails de dados, alimentado pela classificação BlueXP . O recurso de guardrails de dados identifica e mascara informações pessoais identificáveis (PII) ajudando você a manter a conformidade e fortalecer a segurança de seus dados organizacionais confidenciais.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#create-and-configure-the-knowledge-base["Crie uma base de conhecimento"]

link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Saiba mais sobre a classificação BlueXP"^]



== 29 de setembro de 2024



=== Suporte a snapshot e restauração para volumes da base de conhecimento

Agora, você pode proteger seus dados generativos de workloads de AI usando uma cópia pontual de uma base de conhecimento. Isso permite que você proteja seus dados contra perda acidental ou alterações de teste nas configurações da base de conhecimento. Você pode restaurar a versão anterior do volume da base de conhecimento a qualquer momento.

https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html#take-a-snapshot-of-a-knowledge-base-volume["Tire um instantâneo de um volume da base de conhecimento"]

https://review.docs.netapp.com/us-en/workload-genai_29-sept-24-release/manage-knowledgebase.html#restore-a-snapshot-of-a-knowledge-base-volume["Restaurar um snapshot de um volume da base de conhecimento"]



=== Pausar digitalizações programadas

Agora você pode pausar digitalizações de origem de dados agendadas. Por padrão, workloads de AI generativo varre cada fonte de dados diariamente para ingerir novos dados em cada base de conhecimento. Se você não quiser que as alterações mais recentes sejam ingeridas (durante o teste ou durante a restauração de um instantâneo, por exemplo), você pode pausar as verificações agendadas e retomá-las a qualquer momento.

https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html["Gerenciar bases de conhecimento"]



=== Volumes de proteção de dados agora compatíveis com bases de conhecimento

Ao selecionar um volume da base de conhecimento, agora você pode escolher um volume de proteção de dados que faça parte de uma relação de replicação do NetApp SnapMirror. Isso permite armazenar bases de conhecimento em volumes que já estão protegidos pela replicação do SnapMirror.

https://docs.netapp.com/us-en/workload-genai/identify-data-sources.html["Identifique as fontes de dados a serem integradas em sua base de conhecimento"]



== 1 de setembro de 2024



=== Estratégias adicionais de divisão

Agora, as cargas de trabalho generativas de IA oferecem suporte a volumes de várias frases e conjuntos baseados em sobreposição para fontes de dados.



=== Volume dedicado para cada base de conhecimento

Agora, cria um volume dedicado do Amazon FSX for NetApp ONTAP para cada nova base de conhecimento, permitindo políticas de snapshot individuais para cada base de conhecimento e proteção aprimorada contra falhas e envenenamento de dados.



== 4 de agosto de 2024



=== Integração do Amazon CloudWatch Logs

As cargas de trabalho generativas de IA agora estão integradas ao Amazon CloudWatch Logs, permitindo que você monitore arquivos de log de cargas de trabalho generativas de IA.



=== Exemplo de aplicativo chatbot

O aplicativo de amostra GenAI de fábrica de carga de trabalho da NetApp permite testar a autenticação e a recuperação da sua base de conhecimento de fábrica de carga de trabalho da NetApp publicada interagindo diretamente com ela em um aplicativo de chatbot baseado na Web.



== 7 de julho de 2024



=== Lançamento inicial da fábrica de carga de trabalho para o GenAI

A versão inicial inclui a capacidade de desenvolver uma base de conhecimento que é personalizada incorporando os dados da sua organização. A base de conhecimento pode ser acessada por um aplicativo de chatbot para seus usuários. Essa capacidade garante respostas precisas e relevantes a perguntas específicas da organização, aumentando a satisfação e a produtividade de todos os seus usuários.
