---
sidebar: sidebar 
permalink: general/monitor-operations.html 
keywords: monitor genai, monitor jobs, track jobs, tracker 
summary: Acompanhe as operações de carga de trabalho e monitore o progresso do trabalho com o Tracker no NetApp Workload Factory para GenAI. 
---
= Monitore as operações de carga de trabalho com o Tracker no NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Monitore e acompanhe a execução de operações de carga de trabalho e monitore o progresso das tarefas com o Tracker no NetApp Workload Factory.

.Sobre esta tarefa
O NetApp Workload Factory fornece o Tracker, um recurso de monitoramento, para que você possa monitorar e rastrear o progresso e o status das operações de carga de trabalho, revisar detalhes de tarefas e subtarefas de operação e diagnosticar quaisquer problemas ou falhas.

Várias ações estão disponíveis no Tracker. Você pode filtrar tarefas por período de tempo (últimas 24 horas, 7 dias, 14 dias ou 30 dias), carga de trabalho, status e usuário; encontrar trabalhos usando a função de pesquisa; e fazer download da tabela de tarefas como um arquivo CSV. Você pode atualizar o Rastreador a qualquer momento e tentar novamente rapidamente uma operação com falha ou editar parâmetros para uma operação com falha e tentar a operação novamente.

O Tracker suporta dois níveis de monitoramento, dependendo da operação. Cada tarefa, como a implantação do sistema de arquivos, exibe a descrição da tarefa, status, hora de início, duração da tarefa, usuário, região, recurso proxy, ID da tarefa e todas as subtarefas relacionadas. Você pode visualizar as respostas da API para entender o que aconteceu durante a operação.

Monitore níveis de tarefa com exemplos::
+
--
* Nível 1 (tarefa): Controla a implantação do sistema de arquivos.
* Nível 2 (subtarefa): Controla as subtarefas relacionadas com a implementação do sistema de ficheiros.


--
Estado da operação:: O status da operação no Rastreador é o seguinte _em andamento_, _sucesso_ e _falha_.
+
--
Frequência de funcionamento:: A frequência de funcionamento baseia-se no tipo de trabalho e na programação de trabalhos.


--
Retenção de eventos:: Os eventos são mantidos na interface do usuário por 30 dias.




== Monitorizar e monitorizar as operações

Rastreie e monitore operações no console do Workload Factory com o Tracker.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No menu de carga de trabalho, selecione *Administração* e depois selecione *Rastreador*.
. No Tracker, use os filtros ou pesquise para restringir os resultados dos trabalhos. Você também pode baixar um relatório de empregos.




== Exibir solicitação de API

Visualize a solicitação de API na caixa de código para uma tarefa no Tracker.

.Passos
. No Rastreador, selecione uma tarefa.
. Selecione o menu de ações e depois selecione *Exibir solicitação de API*.




== Tente novamente uma operação com falha

Tente novamente uma operação com falha no Tracker. Você também pode copiar a mensagem de erro de uma operação com falha.


NOTE: Você pode tentar novamente uma operação com falha até 10 vezes.

.Passos
. No Rastreador, selecione uma operação com falha.
. Selecione o menu de ações e depois selecione *Repetir*.


.Resultado
A operação é reiniciada.



== Edite e tente novamente uma operação com falha

Edite os parâmetros da operação com falha e tente novamente a operação fora do Rastreador.

.Passos
. No Rastreador, selecione uma operação com falha.
. Selecione o menu de ações e depois selecione *Editar e tentar novamente*.
+
Você é redirecionado para a página de operação, onde você pode editar os parâmetros e tentar novamente a operação.



.Resultado
A operação é reiniciada. Aceda a Rastreador para ver o estado da operação.
