= Clonar uma base de conhecimento a partir de um instantâneo
:allow-uri-read: 




=== Clonar uma base de conhecimento a partir de um instantâneo

O NetApp Workload Factory para GenAI agora oferece suporte à clonagem de uma base de conhecimento a partir de um snapshot.  Isso permite a recuperação rápida de bases de conhecimento e a criação de novas bases de conhecimento com fontes de dados existentes, além de ajudar na recuperação e no desenvolvimento de dados.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/manage-knowledgebase.html#clone-a-knowledge-base["Clonar uma base de conhecimento"]



=== Detecção e replicação de clusters ONTAP no local

Descubra e replique dados de cluster ONTAP locais em um sistema de arquivos FSx for ONTAP para que eles possam ser usados ​​para enriquecer bases de conhecimento de IA.  Todos os fluxos de trabalho de descoberta e replicação no local são possíveis no novo menu *On-Premises ONTAP* no inventário de armazenamento.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/use-onprem-data.html["Descubra um cluster ONTAP no local"]
