= Nome do instantâneo personalizado
:allow-uri-read: 




=== Nome do instantâneo personalizado

Agora você pode fornecer um nome de instantâneo para um instantâneo ad-hoc.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/manage-knowledgebase.html#protect-a-knowledge-base-with-snapshots["Proteja uma base de conhecimento com snapshots"]



=== Nome de instância personalizado do mecanismo de AI

Agora você pode dar um nome personalizado à instância do mecanismo de AI durante a implantação.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/deploy-infrastructure.html["Implantar a infraestrutura do GenAI"]



=== Reconstruir a infraestrutura do GenAI corrompida ou ausente

Se a instância do seu mecanismo de IA for corrompida ou excluída de alguma forma, você pode deixar o Workload Factory reconstruí-la para você.  O Workload Factory reconecta automaticamente suas bases de conhecimento à infraestrutura após a reconstrução ser concluída, para que elas estejam prontas para uso.

link:https://docs.netapp.com/us-en/workload-genai/general/troubleshooting.html["Solução de problemas"]
