---
sidebar: sidebar 
permalink: connector/define-connector.html 
keywords: ai, chatbot, connector, 
summary: Depois de implantar a infraestrutura de IA e identificar as fontes de dados que serão integradas ao Amazon Q Business, é possível definir um conetor. 
---
= Crie um conector NetApp para o Amazon Q Business
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de implantar a infraestrutura de IA e identificar as fontes de dados que você usará dos seus datastores do FSx para ONTAP, você estará pronto para definir um NetApp Connector para o Amazon Q Business.

Certifique-se de que seu ambiente atenda ao link:requirements-connector.html["requisitos"] para Amazon Q Business antes de prosseguir.

.Sobre esta tarefa
Fontes de dados da sua organização podem conter Informações de Identificação Pessoal (PII).  Para proteger essas informações confidenciais, você pode habilitar _guardrails de dados_ ao definir um conector.  Os guardrails de dados, alimentados pela NetApp Data Classification, identificam e mascaram PII, tornando-os inacessíveis e irrecuperáveis.

link:https://docs.netapp.com/us-en/data-services-data-classification/concept-cloud-compliance.html["Saiba mais sobre a classificação de dados da NetApp"^] .


NOTE: O NetApp Workload Factory para GenAI não mascara informações pessoais confidenciais (SPII).  Consultelink:https://docs.netapp.com/us-en/data-services-data-classification/reference-private-data-categories.html#types-of-sensitive-personal-data["tipos de dados pessoais sensíveis"^] para mais informações sobre esse tipo de dados.


NOTE: Os guardrails de dados podem ser ativados ou desativados a qualquer momento.  Se você alternar a ativação dos guardrails de dados, o Workload Factory verificará toda a fonte de dados do zero, o que pode gerar um custo.



== Defina um conetor

Crie um conector NetApp para o Amazon Q Business. O conector permite a comunicação de API e fonte de dados entre a GenAI e o Amazon Q Business.

.Passos
. Faça login no Workload Factory usando um doslink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^] .
. No bloco cargas de trabalho de IA, selecione *Deploy & Manage*.
. No menu Bases de conhecimento e conectores, selecione o menu suspenso *Criar novo* e escolha *Conector Amazon Q Business*.
. Na página Definir conetor, configure as definições do conetor:
+
.. *Nome*: Insira o nome que deseja usar para o conetor.
.. *Descrição*: Introduza uma descrição detalhada do conetor.
.. *Amazon Q*: A região e o nome do aplicativo para a instância do Amazon Q Business que você deseja integrar.
.. *Guardrails de dados*: escolha se deseja habilitar ou desabilitar os guardrails de dados. link:https://docs.netapp.com/us-en/data-services-data-classification/concept-cloud-compliance.html["Saiba mais sobre guardrails de dados, com tecnologia da NetApp Data Classification"^] .
+
Os pré-requisitos a seguir devem ser atendidos para habilitar os corrimões de dados.

+
*** Uma conta de serviço é necessária para se comunicar com o NetApp Data Classification.  Você deve ter a função _Administrador da organização_ na sua conta de locação do NetApp Console para criar uma conta de serviço.  Um membro que tem a função de administrador da organização pode concluir todas as ações no NetApp Console.link:https://docs.netapp.com/us-en/console-setup-admin/task-iam-manage-members-permissions.html#add-a-role-to-a-member["Aprenda como adicionar uma função a um membro no NetApp Console"^]
*** O mecanismo de IA deve ter acesso aolink:https://api.bluexp.netapp.com["Ponto de extremidade da API do console NetApp"^] .
*** Você precisará fazer o seguinte conforme descrito emlink:https://docs.netapp.com/us-en/data-services-data-classification/task-deploy-cloud-compliance.html#quick-start["Documentação de classificação de dados da NetApp"^] :
+
.... Criar um agente de console
.... Certifique-se de que seu ambiente atenda aos pré-requisitos
.... Implantar classificação de dados do NetApp






+

NOTE: Quando você ativa o recurso de guardrails de dados, o GenAI processa arquivos .txt, .md, .csv, .docx e .pdf inserindo apenas texto simples (excluindo imagem incorporada ou texto de Mídia) e mascarando quaisquer dados privados ou confidenciais. Todos os outros tipos de arquivo são processados normalmente sem mascarar dados privados ou confidenciais.

+
.. *FSx para sistema de arquivos ONTAP *: quando você define um novo NetApp Connector para o Amazon Q Business, o Workload Factory cria um novo volume Amazon FSx for NetApp ONTAP para armazenar as informações do conector.  Escolha um sistema de arquivos existente e uma SVM (também chamada de VM de armazenamento) onde o novo volume será criado.
.. *Política de snapshot*: escolha uma política de snapshot na lista de políticas existentes definidas no inventário de armazenamento do Workload Factory.  O GenAI cria automaticamente snapshots recorrentes do volume que armazena as informações do conector em uma frequência baseada na política de snapshot selecionada.
+
Se a política de snapshot que você precisa não existir, você pode https://docs.netapp.com/us-en/ontap/data-protection/create-snapshot-policy-task.html["criar uma política de snapshot"^] na VM de armazenamento que contém o volume.



. Selecione *Create Connector* para integrar o Amazon Q Business com o GenAI.
+
Um indicador de progresso aparece enquanto o conetor é criado.

+
Depois que o conetor é criado, você tem a opção de adicionar uma fonte de dados ao conetor para que o Amazon Q Business ingere seus dados e os adicione ao seu índice. Recomendamos que você selecione *Adicionar fonte de dados* e adicione uma ou mais fontes de dados agora.





== Adicione fontes de dados ao conetor

Você pode adicionar uma ou mais fontes de dados para preencher o índice do Amazon Q Business com os dados da sua organização.

.Sobre esta tarefa
* O número máximo de fontes de dados suportadas é 10.
* Consulte o https://docs.aws.amazon.com/kendra/latest/dg/quotas.html["Documentação do Amazon Q Business"^] para obter restrições de serviço específicas do índice Amazon Q Business.


.Passos
. Depois de selecionar *Adicionar fonte de dados*, a página *Selecionar um sistema de arquivos* é exibida.
. * Selecione um sistema de arquivos*: Selecione o sistema de arquivos FSX for ONTAP onde seus arquivos de origem de dados residem e selecione *Next*.
. *Selecione um volume*: Selecione o volume no qual os arquivos de origem de dados residem e selecione *Next*.
+
Ao selecionar arquivos armazenados usando o protocolo SMB, você precisará inserir as informações do ative Directory, que incluem o domínio, o endereço IP, o nome de usuário e a senha.

. *Selecione uma fonte de dados*: Selecione a localização da fonte de dados com base no local onde você salvou os arquivos. Este pode ser um volume inteiro, ou apenas uma pasta específica ou subpasta no volume, e selecione *Next*.
. * Configurações*: Configure como a fonte de dados ingere informações de seus arquivos e quais arquivos ela inclui em varreduras:
+
** * Filtragem de arquivos*: Configure quais arquivos estão incluídos nas digitalizações:
+
*** Na seção *suporte a tipos de arquivo*, escolha incluir todos os tipos de arquivos ou selecionar tipos de arquivo individuais para inclusão nas verificações de origem de dados.
*** Na seção *filtro de tempo de modificação de arquivo*, escolha ativar ou desativar a inclusão de arquivos com base em seu tempo de modificação. Se ativar a filtragem de hora de modificação, selecione um intervalo de datas na lista.
+

NOTE: Se você incluir arquivos com base em um intervalo de datas de modificação, assim que o intervalo de datas não for satisfeito (os arquivos não foram modificados dentro do intervalo de datas especificado), os arquivos serão excluídos da verificação periódica e a fonte de dados não incluirá esses arquivos.





. Na seção *reconhecimento de permissão*, que está disponível somente quando a fonte de dados selecionada estiver em um volume que usa o protocolo SMB, você pode ativar ou desativar respostas com reconhecimento de permissão:
+
** *Enabled*: Os usuários do chatbot que acessarem este conetor receberão apenas respostas a consultas de fontes de dados às quais tenham acesso.
** *Disabled*: Os usuários do chatbot receberão respostas usando conteúdo de todas as fontes de dados integradas.
+

NOTE: As permissões de grupo do ative Directory não são suportadas para fontes de dados do Amazon Q Business Connector.



. Selecione *Adicionar* para adicionar essa fonte de dados ao Amazon Q Business Connector.


.Resultado
A fonte de dados está incorporada ao índice do Amazon Q Business. O status muda de "incorporação" para "incorporada" quando a fonte de dados está completamente incorporada.

Depois de adicionar uma única fonte de dados ao conetor, você pode testá-la no ambiente de chatbot do Amazon Q Business e fazer as alterações necessárias antes de disponibilizar o serviço aos usuários. Você também pode seguir os mesmos passos para adicionar fontes de dados adicionais ao conetor.
